name: github-Actions-CI
on: 
    push:
        branches:
            - ci-aws
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            
            - name: configure aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ap-south-1

            - name: search and replace the auth key
              run: |
                export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vprofile --domain-owner 367065853931 --region ap-south-1 --query authorizationToken --output text`
                sed -i "s/env.CODEARTIFACT_AUTH_TOKEN/`echo $CODEARTIFACT_AUTH_TOKEN`/" settings.xml

            - name: setup JDK and maven
              uses: actions/setup-java@v3
              with: 
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            
            - name: Maven test
              run: mvn -s settings.xml test
            
            - name: Checkstyle
              run: mvn -s settings.xml checkstyle:checkstyle
            
            - name: SonarQube Scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              with:
                args: >
                  -Dsonar.organization=sonar-vprofile
                  -Dsonar.projectKey=sonar-vprofile-org
                  -Dsonar.projectVersion=1.0
                  -Dsonar.sources=src/
                  -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
                  -Dsonar.junit.reportsPath=target/surefire-reports/
                  -Dsonar.jacoco.reportsPath=target/jacoco.exec
                  -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml