name: github-Actions-CI
on: 
    push:
        branches:
            - main
jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            
            - name: configure aws
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ap-south-1

            - name: search and replace the auth key
              run: |
                export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain vprofile --domain-owner 367065853931 --region ap-south-1 --query authorizationToken --output text`
                sed -i "s/env.CODEARTIFACT_AUTH_TOKEN/`echo $CODEARTIFACT_AUTH_TOKEN`/" settings.xml

            - name: setup JDK and maven
              uses: actions/setup-java@v3
              with: 
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            
            - name: Maven test
              run: mvn test
            
            - name: Checkstyle
              run: mvn checkstyle:checkstyle

            - name: Setup SonarQube
              uses: warchant/setup-sonar-scanner@v7
            

            - name: SonarQube Scan
              run: sonar-scanner
                   -Dsonar.host.url=https://sonarcloud.io
                   -Dsonar.login=${{ secrets.SONAR_TOKEN }}
                   -Dsonar.organization=sonar-vprofile
                   -Dsonar.projectKey=sonar-vprofile-org
                   -Dsonar.projectVersion=1.0
                   -Dsonar.sources=src/
                   -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
                   -Dsonar.junit.reportsPath=target/surefire-reports/
                   -Dsonar.jacoco.reportsPath=target/jacoco.exec
                   -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

    Build_and_Publish:
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v4
        
        - name: Update application.properties
          run: |
            sed -i "s/db01/${{ secrets.RDS_ENDPOINT }}/" src/main/resources/application.properties

        - name: upload image to ECR
          uses: appleboy/docker-ecr-action@master
          with:
              access_key: ${{ secrets.AWS_ACCESS_KEY }}
              secret_key: ${{ secrets.AWS_SECRET_KEY }}
              registry: 367065853931.dkr.ecr.ap-south-1.amazonaws.com
              repo: vprofile-app
              region: ap-south-1
              tags: latest,${{ github.run_number }}
              daemon_off: false
              dockerfile: ./Dockerfile
              context: ./
        
        - name: upload image to ECR
          uses: appleboy/docker-ecr-action@master
          with:
            access_key: ${{ secrets.AWS_ACCESS_KEY }}
            secret_key: ${{ secrets.AWS_SECRET_KEY }}
            registry: 367065853931.dkr.ecr.ap-south-1.amazonaws.com
            repo: vprofile-cb
            region: ap-south-1
            tags: latest,${{ github.run_number }}
            daemon_off: false
            dockerfile: Docker/db/Dockerfile
            context: Docker
